from format_docs.elastic_guide import format_to_doc as format_elastic_guides
from format_docs.elastic_api_spec import format_to_doc as format_elastic_api_specs


from format_docs.elastic_guide import title as create_guide_title
from format_docs.elastic_api_spec  import title as create_api_spec_title